apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-datsko
  namespace: {{ namespace }}
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: datsko-web
  template:
    metadata:
      labels:
        app: datsko-web
    spec:
      containers:
      - name: app
        image: sofiiadatsko/app:{{ tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000 # Django працює тут
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: {{ namespace }}
spec:
  # Прибрали NodePort, лишаємо ClusterIP за замовчуванням
  selector:
    app: datsko-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000 # Направляємо на порт застосунку
