- hosts: all
  become: yes
  tasks:
    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name: [apt-transport-https, ca-certificates, curl, software-properties-common, docker.io]
        state: present

    - name: Install Minikube
      shell: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube /usr/local/bin/
      args:
        creates: /usr/local/bin/minikube

    - name: Install kubectl (Kubernetes CLI)
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Start Minikube with Docker driver
      shell: minikube start --driver=docker --force
      become_user: root

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Setup Proxy for Minikube Access
      shell: |
        # Запускаємо проксі у фоновому режимі, щоб мати доступ до API
        nohup kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' > /dev/null 2>&1 &
