name: Deploy App to Kubernetes
on:
  push:
    branches: [ develop ]
    tags: [ '1.0.0' ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Логін в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Збірка та Пуш
      - name: Build and push
        run: |
          TAG=${GITHUB_REF_NAME}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app:$TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app:$TAG

      # 3. Розгортання через SSH
      - name: Deploy to Minikube via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Визначаємо змінні на основі того, що прийшло з GitHub
            TAG=${{ github.ref_name }}
            NAMESPACE=${{ github.ref_type == 'tag' && 'release' || 'dev' }}
            PORT=${{ github.ref_type == 'tag' && '8003' || '8002' }}
            
            # Створюємо namespace, якщо його немає
            kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
            
            # Отримуємо файл маніфесту (заміни 'main' на свою поточну гілку, якщо треба)
            # Або краще: просто скопіюй його зміст через cat, якщо файл невеликий
            curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/task3/deployment.yaml -o deployment.yaml
            
            # ЗАМІНА ЗМІННИХ (sed)
            sed -i "s/{{ namespace }}/$NAMESPACE/g" deployment.yaml
            sed -i "s/{{ tag }}/$TAG/g" deployment.yaml
            sed -i "s/{{ port }}/$PORT/g" deployment.yaml
            
            # ПЕРЕВІРКА ПЕРЕД РОЗГОРТАННЯМ (Requirement: Dry-run)
            kubectl apply -f deployment.yaml --dry-run=client
            
            # РЕАЛЬНЕ РОЗГОРТАННЯ
            kubectl apply -f deployment.yaml
            
            # СТАТУС РОЗГОРТАННЯ
            kubectl rollout status deployment/app-datsko -n $NAMESPACE --timeout=60s
